services:
  backend-app:
    build: .
    container_name: backend-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/employee_db

  mongo:
    image: mongo:7
    container_name: backend-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: